// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgb4lzRf04ChTnz9baAWPIX4plNpWmJqQ',
    appId: '1:530001069485:web:aea676ef6e1534c7b34d24',
    messagingSenderId: '530001069485',
    projectId: 'qiratperfumes',
    authDomain: 'www.qiratshop.in',
    storageBucket: 'qiratperfumes.appspot.com',
    measurementId: 'G-VDRTZQEW7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rmXn2Fa_b8S5PU5wPVmihzAVWEB_JOc',
    appId: '1:530001069485:android:5e1891cec1ba894fb34d24',
    messagingSenderId: '530001069485',
    projectId: 'qiratperfumes',
    storageBucket: 'qiratperfumes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC0pTv8QTDXu6oENUF14l2WJmw0FjG1pg',
    appId: '1:530001069485:ios:c9c74f7708e1cb54b34d24',
    messagingSenderId: '530001069485',
    projectId: 'qiratperfumes',
    storageBucket: 'qiratperfumes.appspot.com',
    androidClientId: '530001069485-4hnlmpk585qhsm8fbq8egtjtf7d73r03.apps.googleusercontent.com',
    iosClientId: '530001069485-6g20bpgr9ji7pk7vsgm1adm9m4086gb0.apps.googleusercontent.com',
    iosBundleId: 'com.ak.qiratshop',
  );

}