// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgb4lzRf04ChTnz9baAWPIX4plNpWmJqQ',
    appId: '1:530001069485:web:aea676ef6e1534c7b34d24',
    messagingSenderId: '530001069485',
    projectId: 'qiratperfumes',
    authDomain: 'qiratperfumes.firebaseapp.com',
    storageBucket: 'qiratperfumes.appspot.com',
    measurementId: 'G-VDRTZQEW7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rmXn2Fa_b8S5PU5wPVmihzAVWEB_JOc',
    appId: '1:530001069485:android:bdd328663268a38eb34d24',
    messagingSenderId: '530001069485',
    projectId: 'qiratperfumes',
    storageBucket: 'qiratperfumes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC0pTv8QTDXu6oENUF14l2WJmw0FjG1pg',
    appId: '1:530001069485:ios:5375c95f29d2da17b34d24',
    messagingSenderId: '530001069485',
    projectId: 'qiratperfumes',
    storageBucket: 'qiratperfumes.appspot.com',
    iosBundleId: 'com.example.eshop.eshop',
  );
}
